# Generated by Django 3.0.5 on 2020-04-21 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('cookie_id', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('banner_id', models.IntegerField(blank=True)),
                ('banner_pos', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['user_id', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BannerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('location_id', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='BannerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('product_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
            options={
                'ordering': ['banner_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('product_id', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('cookie_id', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['user_id', 'timestamp'],
            },
        ),
    ]
