# Generated by Django 3.0.5 on 2020-05-27 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('status', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('last_update', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.DeleteModel(
            name='BannerLocation',
        ),
        migrations.AlterModelOptions(
            name='bannerinteractions',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='productinteractions',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='banner_id',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
