# Generated by Django 3.0.5 on 2020-05-28 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0002_auto_20200527_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerstatus',
            name='banner_id',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
