# Generated by Django 3.0.5 on 2020-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0003_auto_20200528_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerstatus',
            options={'ordering': ['-status']},
        ),
        migrations.AddField(
            model_name='bannerinteractions',
            name='source',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
