# Generated by Django 3.0.5 on 2020-06-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0004_auto_20200609_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerStatus',
        ),
    ]
