# Generated by Django 3.0.5 on 2020-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0006_bannerstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerProduct',
        ),
    ]
