# Generated by Django 3.0.5 on 2020-06-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0008_bannerproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerProduct',
        ),
    ]
