# Generated by Django 3.0.5 on 2020-06-15 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0009_delete_bannerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('product_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
            options={
                'ordering': ['banner_id'],
            },
        ),
    ]
