# Generated by Django 3.0.5 on 2020-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0010_bannerproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerStatus',
        ),
    ]
