# Generated by Django 3.0.5 on 2020-06-15 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0011_delete_bannerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('status', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('last_update', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
